### ISSUE TITLE
Cannot connect to dev server on port 8080

### ISSUE THREAD

**Issue by russau** [jakedeichert/react-starter#19]
Hi,

Hopefully you are able to help.  I'm running the docker container just as the instructions spell out.  When I `yarn run dev` I cannot connect from my docker host.  I.e. I'm running docker on a AWS EC2 Amazon Linux host, from the host a curl gives:

```
$ curl localhost:8080
curl: (56) Recv failure: Connection reset by peer
```

If I attach to the docker container I'm able to `curl localhost:8080` just fine.

I defn have my ports mapped correctly, as I'm able to connect from the host when I run `yarn run build:prod && http-server /var/www/html/dist`.

Is there an additional setting I'm missing to allow these connections into the dev server?

Thanks!
Russ

**Comment by jakedeichert** [comment]
Hey! Hopefully I can help out a little.

First, the Dockerfile provided I only intended to be used for local development, and I didn't expect anyone to really use my starter kit, but here we are 😅 

So it sounds like you are running docker on an ec2 server. And you're saying that while you are ssh'd into that server, running curl on 8080 fails? But, if you connect to the docker container interactively, and run curl inside that, it responds properly?

Running curl, outside the container as you did, should have worked fine. Have you tried this locally first? Assuming it works locally on your pc, and you used the same docker build command on the ec2 server, it should have worked.

There's no other configuration options actually. Just the docker build command as the readme shows.

Let me know if you have any more details, or if you get it working 👍

**Comment by russau** [comment]
Hi!

- docker on an ec2 server ✅
- ssh'd into that server, running curl on 8080 fails ✅
- exec bash on the container and curl works  ✅

Could it be that the webpack-dev-server is throwing away the connection as it appears to be an external connection? Telnet to port 8080 has the same behaviour. My first thought was that I had the ports mapped wrong, but http-server is happy.

I'll play around with installing everything on the instance minus docker and see if that works for me.

Thanks!
Russ

**Comment by jakedeichert** [comment]
Ahh, http-server works fine with curl? Then yes, perhaps webpack-dev-server isn't liking curl for some reason, which still doesn't make a lot of sense to me.

Actually, I'm a little curious as to why you'd want to run the dev server on ec2? Understandable if you are using ec2 as a dev environment I suppose. 

Let me know if you figure out what the issue is. I'll do a bit of digging to see if I can find out why this wouldn't work.

**Comment by jakedeichert** [comment]
Hmmm, this sounds like a solution https://webpack.js.org/configuration/dev-server/#devserver-host-cli-only

> Specify a host to use. By default this is localhost. If you want your server to be accessible externally, specify it like this:

'host: "0.0.0.0"'

**Comment by russau** [comment]
Hello again,

Bingo! 👍

> curious as to why you'd want to run the dev server on ec2

It's a work rule I have - easier to boot up an instance.

Thanks again!
Russ

**Comment by jakedeichert** [comment]
Great! Glad it worked out :)

**Comment by jakedeichert** [comment]
Just mentioning, I implemented the fix for webpack now as well. It turns out, webpack-dev-server released a security update as a patch version even though it was a breaking change... which I didn't realize until now and this is why it wasn't working for you 2 weeks ago.

Check out my commit to see more info: https://github.com/jakedeichert/react-starter/commit/ef237bc75fc5a1a9c657981f04cf6cb947ea1cee

* webpack/webpack-dev-server#887
* https://github.com/webpack/webpack-dev-server/releases/tag/v2.4.3
* webpack/webpack-dev-server#882
* https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a

**Comment by russau** [comment]
Very interesting!  Wasn't aware of the dns rebinding attacks.  Thanks for the info!
